In [1]:
import pandas as pd
import numpy as np
import sklearn

from sklearn import linear_model
from sklearn import metrics
from sklearn import preprocessing

import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')

with open('WebscopeReadMe.txt', 'r') as file:
    readme_contents = file.read()

print(readme_contents)

In [2]:
with open('README.txt', 'r') as file:
    readme_contents = file.read()

print(readme_contents)

Dataset: ydata-labeled-time-series-anomalies-v1_0

Yahoo! Synthetic and real time-series with labeled anomalies, version 1.0

=====================================================================
This dataset is provided as part of the Yahoo! Webscope program, to be
used for approved non-commercial research purposes by recipients who
have signed a Data Sharing Agreement with Yahoo!. This dataset is not
to be redistributed. No personally identifying information is available
in this dataset. More information about the Yahoo! Webscope program is
available at http://research.yahoo.com

=====================================================================

Full description:

This dataset contains 371 files:

A1Benchmark/real_(int).csv
A2Benchmark/synthetic_(int).csv
A3Benchmark/A3Benchmark-TS(int).csv
A4Benchmark/A4Benchmark-TS(int).csv

A1Benchmark is based on the real production traffic to some of the Yahoo! properties.
The other 3 benchmarks are based on synthetic time-series. A2 and A3 Benchmarks include outliers,
while the A4Benchmark includes change-point anomalies. The bechmarks based on real-data have property
and geos removed. Fields in each data file are delimited with (",") characters.

The content of the six files are as follows:

=====================================================================
(1) "A[1-2]Benchmark/[real,synthetic]_(int).csv" contains real and synthetic time-series with labeled anomalies.
    The synthetic data set contains time-series with random seasonality, trend and noise. The outliers in the
    synthetic dataset are inserted at random positions. Note that the timestamps of the A1Benchmark are replaced by
    integers with the increment of 1, where each data-point represents 1 hour worth of data. The anomalies in A1Benchmark
    are marked by humans and therefore may not be consistent, therefore during benchmarking A1Benchmark is best used to measure
    recall.

    The fields are:

    0 timestamp
    1 value
    2 is_anomaly

    The is_anomaly field is a boolean indicating if the current value at a given timestamp is considered an anomaly.

Snippet:
  1,83,0
  2,605,0
  3,181,0
  4,37,0
  5,45,1

=====================================================================
(2) "A[3-4]Benchmark/A[3-4]Benchmark-TS(int).csv" contain synthetic time-series.
     The A3Benchmark only contains outliers while the A4Benchmark also contains the anomalies
     that are marked as change-points. The synthetic time-series have varying noise and trends
     with three pre-specified seasonalities. The anomalies in the synthetic time-series are inserted at random positions.
     The fields are:

    0 timestamps: the UNIX timestamp marks every hour (the data is hourly sampled)
    1 value: the value of time series at this timestamp
    2 anomaly: 1 if this stamp is an outlier
    3 changepoint: 1 if this stamp is a change point
    4 trend: the additive trend value for this timestamp
    5 noise: the additive noise value for this timestamp
    6 seasonality1: the 12-hour seasonality value
    7 seasonality2: the daily seasonality value
    8 seasonality3: the weekly seasonality value

Snippet:

1422237600,4333.43325915382,0,0,4599,1.81512268926974,-190.958601534458,-128.864580083128,52.4413180821374
1422241200,4316.14322293657,0,0,4602,-14.6572208523525,-220.5,-105.217489040563,54.5179328294825
1422244800,4403.20006523115,0,0,4605,7.04036744752875,-190.958601534463,-74.3999999999969,56.5182993180795
1422248400,4531.20632084718,0,0,4608,13.5289749039305,-110.250000000009,-38.5122739112586,58.4396198545142
1422252000,4967.50678185938,1,0,4911,-3.7724254388993,-6.91288625182698e-12,-2.33251127952801e-12,60.279207

In [3]:
data1=pd.read_csv("./A1Benchmark/real_1.csv") #training data set1
data1.head(10)

   timestamp     value  is_anomaly
0          1  0.000000           0
1          2  0.091758           0
2          3  0.172297           0
3          4  0.226219           0
4          5  0.176358           0
5          6  0.090491           0
6          7  0.084610           0
7          8  0.068427           0
8          9  0.133303           0
9         10  0.085027           0

In [4]:
data2=pd.read_csv("./A2Benchmark/synthetic_1.csv") #training data set1
data2.head(10)

    timestamp       value  is_anomaly
0  1416726000   13.894031           0
1  1416729600   33.578274           0
2  1416733200   88.933746           0
3  1416736800  125.389424           0
4  1416740400  152.962000           0
5  1416744000  168.365150           0
6  1416747600  211.863425           0
7  1416751200  255.452289           0
8  1416754800  295.065010           0
9  1416758400  357.805877           0

In [5]:
data3=pd.read_csv("./A3Benchmark/A3Benchmark-TS1.csv") #training data set1
data3.head(10)

,timestamps,value,anomaly,changepoint,trend,noise,seasonality1,seasonality2,seasonality3
0,1.416722e+09,-363.278909,0,0,-2,-361.278909,0.000000e+00,0.000000,0.000000
1,1.416726e+09,320.888590,0,0,-4,-217.845824,4.131000e+02,115.769759,13.864655
2,1.416730e+09,891.727422,0,0,-6,-69.142686,7.155102e+02,223.650000,27.709919
3,1.416733e+09,1174.652287,0,0,-8,-1.353004,8.262000e+02,316.288863,41.516428
4,1.416737e+09,1712.290261,0,0,-10,564.142037,7.155102e+02,387.373163,55.264872
5,1.416740e+09,1081.236959,0,0,-12,179.142313,4.131000e+02,432.058622,68.936024
6,1.416744e+09,328.359753,0,0,-14,-187.451010,1.011803e-13,447.300000,82.510762
7,1.416748e+09,-170.316551,0,0,-16,-269.245275,-4.131000e+02,432.058622,95.970102
8,1.416751e+09,-304.750738,0,0,-18,-67.908931,-7.155102e+02,387.373163,109.295219
9,1.416755e+09,-477.640815,0,0,-20,-70.197155,-8.262000e+02,316.288863,122.467476

In [6]:
data4=pd.read_csv("./A4Benchmark/A4Benchmark-TS1.csv") #training data set1
data4.head(10)

,timestamps,value,anomaly,changepoint,trend,noise,seasonality1,seasonality2,seasonality3
0,1.416722e+09,2.889225,0,0,3,-0.110775,0.000000e+00,0.000000,0.000000
1,1.416726e+09,112.492219,0,0,6,46.188395,4.590000e+01,12.863307,1.540517
2,1.416730e+09,131.097056,0,0,9,14.667044,7.950113e+01,24.850000,3.078880
3,1.416733e+09,128.208836,0,0,12,-15.347308,9.180000e+01,35.143207,4.612936
4,1.416737e+09,121.639029,0,0,15,-22.044107,7.950113e+01,43.041463,6.140541
5,1.416740e+09,114.006116,0,0,18,-5.559955,4.590000e+01,48.006514,7.659558
6,1.416744e+09,74.120562,0,0,21,-5.747301,1.124226e-14,49.700000,9.167862
7,1.416748e+09,28.865590,0,0,24,-7.904268,-4.590000e+01,48.006514,10.663345
8,1.416751e+09,7.528932,0,0,27,4.844688,-7.950113e+01,43.041463,12.143913
9,1.416755e+09,-30.181247,0,0,30,-17.131952,-9.180000e+01,35.143207,13.607497