In [1]:
import pandas as pd
import glob

# Assuming all CSV files are in the same directory
files = glob.glob('*.csv')

# Initialize an empty DataFrame
all_data = pd.DataFrame()

# Loop through all CSV files and concatenate the data
for file in files:
    # Assuming the files have a header, if not, set header=None
    data = pd.read_csv(file)
    all_data = pd.concat([all_data, data], axis=0)

# Resetting the index of the concatenated DataFrame
all_data = all_data.reset_index(drop=True)

# Display the resulting DataFrame
print(all_data)

          timestamps        value  anomaly  changepoint  trend      noise  \
0       1.416722e+09    -2.356612        0            0     -1  -1.356612
1       1.416726e+09   432.757886        0            0     -2  11.059252
2       1.416730e+09   766.399413        0            0     -3   8.139552
3       1.416733e+09   939.943011        0            0     -4  -4.067245
4       1.416737e+09   956.790859        0            0     -5   5.227944
...              ...          ...      ...          ...    ...        ...
167995  1.422752e+09 -5268.982723        0            0  -5028   0.208893
167996  1.422756e+09 -5368.375881        0            0  -5031 -47.534669
167997  1.422760e+09 -5338.276465        0            0  -5034 -15.707491
167998  1.422763e+09 -5223.508339        0            0  -5037  45.808345
167999  1.422767e+09 -5173.001790        0            0  -5040  -3.529305

        seasonality1  seasonality2  seasonality3
0           0.000000      0.000000      0.000000
1         291.300000    118.332067     14.066567
2         504.546400    228.600000     28.113461
3         582.600000    323.289220     42.121036
4         504.546400    395.946815     56.069701
...              ...           ...           ...
167995    -90.600000   -128.468135    -22.123481
167996   -156.923803   -115.181379    -17.736030
167997   -181.200000    -94.045202    -13.323773
167998   -156.923803    -66.500000     -8.892881
167999    -90.600000    -34.422933     -4.449552

[168000 rows x 9 columns]

In [9]:
len(all_data.axes[0])

168000

In [18]:
all_data.head(100)

,timestamps,value,anomaly,changepoint,trend,noise,seasonality1,seasonality2,seasonality3
0,1.416722e+09,-2.356612,0,0,-1,-1.356612,0.000000e+00,0.000000e+00,0.000000
1,1.416726e+09,432.757886,0,0,-2,11.059252,2.913000e+02,1.183321e+02,14.066567
2,1.416730e+09,766.399413,0,0,-3,8.139552,5.045464e+02,2.286000e+02,28.113461
3,1.416733e+09,939.943011,0,0,-4,-4.067245,5.826000e+02,3.232892e+02,42.121036
4,1.416737e+09,956.790859,0,0,-5,5.227944,5.045464e+02,3.959468e+02,56.069701
...,...,...,...,...,...,...,...,...,...
95,1.417064e+09,-662.348987,0,0,-96,-6.277540,-2.913000e+02,-1.183321e+02,-150.439380
96,1.417068e+09,-261.207166,0,0,-97,-0.980104,-1.141567e-12,-4.479268e-13,-163.227063
97,1.417072e+09,126.114320,0,0,-98,-9.731289,2.913000e+02,1.183321e+02,-175.786458
98,1.417075e+09,442.147349,0,0,-99,-3.899051,5.045464e+02,2.286000e+02,-188.100000
99,1.417079e+09,610.840495,0,0,-100,5.101742,5.826000e+02,3.232892e+02,-200.150467

In [16]:
a=all_data['anomaly']==1

In [17]:
print(a)

0         False
1         False
2         False
3         False
4         False
          ...
167995    False
167996    False
167997    False
167998    False
167999    False
Name: anomaly, Length: 168000, dtype: bool

In [24]:
all_data.to_csv('file', sep=',', index=False, encoding='utf-8')

In [25]:
df = pd.read_csv('file')

In [26]:
df.head()

,timestamps,value,anomaly,changepoint,trend,noise,seasonality1,seasonality2,seasonality3
0,1.416722e+09,-2.356612,0,0,-1,-1.356612,0.0000,0.000000,0.000000
1,1.416726e+09,432.757886,0,0,-2,11.059252,291.3000,118.332067,14.066567
2,1.416730e+09,766.399413,0,0,-3,8.139552,504.5464,228.600000,28.113461
3,1.416733e+09,939.943011,0,0,-4,-4.067245,582.6000,323.289220,42.121036
4,1.416737e+09,956.790859,0,0,-5,5.227944,504.5464,395.946815,56.069701